language: objective-c
osx_image: xcode9
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
  - brew update
  - brew reinstall xctool
script:
  - xcodebuild -showsdks
  - xcodebuild -project VolumeBar/VolumeBar.xcodeproj -scheme VolumeBar -sdk iphonesimulator11.0 build analyze

